# Generated by Django 4.2.1 on 2023-05-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.CharField(max_length=256)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=256)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
    ]
