# Generated by Django 4.2.1 on 2023-05-15 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainteanance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainteanance',
            name='vendor',
        ),
    ]
